package com.example.ui

enum class AppLanguage(val code: String, val displayName: String, val nativeName: String) {
    KURDISH_BADINI("ku-badini", "Kurdî (Badîni)", "کوردی (بادینی)"),
    KURDISH_SORANI("ku-sorani", "Kurdî (Soranî)", "کوردی (سۆرانی)"),
    ENGLISH("en", "English", "English")
}

object Strings {
    fun get(key: String, lang: AppLanguage): String {
        return when (lang) {
            AppLanguage.KURDISH_BADINI -> kurdishBadiniStrings[key] ?: englishStrings[key] ?: key
            AppLanguage.KURDISH_SORANI -> kurdishSoraniStrings[key] ?: englishStrings[key] ?: key
            AppLanguage.ENGLISH -> englishStrings[key] ?: key
        }
    }

    private val kurdishBadiniStrings = mapOf(
        "app_title" to "M1955 Cinema",
        "tagline" to "سینەمایا کوردی و جیهانی ل بەر دەستێ تە",
        "tab_home" to "سەرەکی",
        "tab_categories" to "پۆلین",
        "tab_add" to "فلمێ نوی",
        "tab_watchlist" to "لیستا من",
        "tab_settings" to "ڕێکخستن",
        "search_hint" to "ل فلمان، ئەکتەران یان دەرهێنەران بگەڕی...",
        "featured" to "هەڵبژارتیێن ئەڤرۆ",
        "trending" to "ب ناوبانگترین",
        "kurdish_cinema" to "سینەمای کوردی 🌟",
        "M1955_cinema" to "سینەمای کوردی 🌟",
        "continue_watching" to "بەردەوامبە ل تەماشەکرنێ",
        "top_rated" to "باشترین نرخاندن",
        "recently_added" to "نویترین فلمان",
        "watch_now" to "تەماشە بکە",
        "trailer" to "ترەیلەر",
        "download" to "داگرتن",
        "add_to_list" to "+ لیستا من",
        "in_list" to "✓ د لیستێ دایە",
        "share" to "پارڤەکرن",
        "synopsis" to "کورتیا چیڕۆکێ",
        "cast_director" to "دەرهێنەر و ئەکتەر",
        "director" to "دەرهێنەر",
        "cast" to "ئەکتەرێن سەرەکی",
        "languages" to "زمان و ژێرنووس",
        "quality" to "کوالیتی",
        "reviews" to "بۆچوون و نرخاندن",
        "add_review" to "بۆچوونا خۆ بنڤیسە",
        "submit_review" to "هنارتنا بۆچوونێ",
        "your_rating" to "نرخاندنا تە",
        "your_name" to "ناڤێ تە",
        "your_comment" to "سەرنج و بۆچوونا تە ل دۆر فلمی...",
        "no_reviews" to "هێشتا چ بۆچوون نەهاتینە تۆمارکرن. ئێکەمین کەس بە!",
        "add_movie_title" to "فلمەکی نوو زێدە بکە",
        "add_movie_subtitle" to "فلمێ خۆ پێکبینە دا هەمی کەس بشێن تەماشە بکەن",
        "movie_title_en" to "ناڤێ فلمی ب ئینگلیزی",
        "movie_title_ku" to "ناڤێ فلمی ب کوردی",
        "movie_category" to "پۆلینا فلمی",
        "movie_release_year" to "ساڵا بەرهەمهێنانێ",
        "movie_duration" to "دەما فلمی (ب خولەک)",
        "movie_video_url" to "لینکا ڤیدیۆیێ یان پەخشێ (Stream Link)",
        "movie_poster_select" to "وێنەیێ پۆستەرێ فلمی",
        "movie_synopsis_ku" to "کورتیا چیرۆکێ ب کوردی",
        "movie_synopsis_en" to "کورتیا چیرۆکێ ب ئینگلیزی",
        "save_movie" to "فلمی تۆمار بکە و بەلاڤ بکە",
        "movie_added_success" to "فلم ب سەرکەفتیانە هاتە زێدەکرن! نوکە هەمی کەس دشێن تەماشە بکەن.",
        "fill_required_fields" to "تکایە ناڤێ فلمی و بەستەرا ڤیدیۆیێ پر بکە",
        "watchlist_empty" to "چ فلم د لیستا تە دا نینن",
        "watchlist_empty_desc" to "د دەمێ تەماشەکرنا فلمان دا دەست بدە سەر + دا بهێنە لیستا تە",
        "video_player_quality" to "کوالیتی",
        "video_player_audio" to "دەنگێ کوردی/ئەسڵی",
        "video_player_subtitles" to "ژێرنووس",
        "speed" to "خێرایی",
        "resume" to "دەستپێکرنەڤە",
        "settings_language" to "زمانێ بەرنامەی",
        "settings_stream_quality" to "کوالیتییا ستاندارد",
        "settings_auto_play" to "لێدانا خۆکار یا داهاتی",
        "settings_stats" to "ئامارێن فلمان",
        "total_movies" to "سەرجەمێ فلمان",
        "user_movies" to "فلمان تە زێدەکرین",
        "all_categories" to "هەمی",
        "genre_action" to "ئەکشن",
        "genre_kurdish" to "سینەمای کوردی",
        "genre_drama" to "دراما",
        "genre_animation" to "ئەنیمەیشن",
        "genre_scifi" to "زانستی خەیاڵی",
        "genre_comedy" to "کۆمیدی",
        "genre_documentary" to "بەڵگەنامەیی",
        "select_preset_poster" to "یان ئێک ژ ڤان پۆستەران هەڵبژێرە:",
        "pick_image_gallery" to "هەڵبژاردنی پووستەر لە تەلەفۆن",
        "uploading_poster" to "بارکردنی وێنە بۆ Firebase Storage...",
        "upload_success" to "وێنە ب سەرکەفتیانە هاتە بارکرن!",
        "custom_poster_selected" to "پووستەرێ تەلەفۆنا تە",
        "poster_url_title" to "لینکا وێنەیێ پۆستەری (Poster Image URL)",
        "poster_url_hint" to "https://example.com/poster.jpg یان لینکا گوگل",
        "poster_url_desc" to "لینکا وێنەیێ پۆستەری ژ گووگل یان هەر مالپەڕەکی ل ڤێرێ دابنێ دا ڕاستەوخۆ دەربکەڤیت.",
        "live_preview_title" to "پێشبینینا ڕاستەوخۆ یا پۆستەری (Live Preview)"
    )

    private val kurdishSoraniStrings = mapOf(
        "app_title" to "M1955 Cinema",
        "tagline" to "سینەمای کوردی و جیهانی لە بەردەستتدا",
        "tab_home" to "سەرەکی",
        "tab_categories" to "پۆلەکان",
        "tab_add" to "فیلمی نوێ",
        "tab_watchlist" to "لیستەکەم",
        "tab_settings" to "ڕێکخستن",
        "search_hint" to "بگەڕێ بۆ فیلم، ئەکتەر یان دەرهێنەر...",
        "featured" to "هەڵبژێردراوەکانی ئەمڕۆ",
        "trending" to "بەناوبانگترینەکان",
        "kurdish_cinema" to "سینەمای کوردی 🌟",
        "M1955_cinema" to "سینەمای کوردی 🌟",
        "continue_watching" to "بەردەوامبە لە سەیرکردن",
        "top_rated" to "بەرزترین پلەبەندی",
        "recently_added" to "نوێترین فیلمەکان",
        "watch_now" to "سەیر بکە",
        "trailer" to "ترەیلەر",
        "download" to "داگرتن",
        "add_to_list" to "+ لیستی من",
        "in_list" to "✓ لە لیستدایە",
        "share" to "هاوبەشکردن",
        "synopsis" to "کورتەی چیرۆک",
        "cast_director" to "دەرهێنەر و ئەکتەرەکان",
        "director" to "دەرهێنەر",
        "cast" to "ئەکتەرەکان",
        "languages" to "زمان و ژێرنووس",
        "quality" to "کوالیتی",
        "reviews" to "بۆچوون و نرخاندنەکان",
        "add_review" to "بۆچوونێک بنووسە",
        "submit_review" to "ناردنی بۆچوون",
        "your_rating" to "نرخاندنی تۆ",
        "your_name" to "ناوت",
        "your_comment" to "سەرنج و بۆچوونت لەسەر فیلمەکە...",
        "no_reviews" to "هێشتا هیچ بۆچوونێک نییە. یەکەم کەس بە!",
        "add_movie_title" to "فیلمێکی نوێ زیاد بکە",
        "add_movie_subtitle" to "فیلمەکەت دابنێ بۆ ئەوەی هەمووان بتوانن سەیری بکەن",
        "movie_title_en" to "ناوی فیلم بە ئینگلیزی",
        "movie_title_ku" to "ناوی فیلم بە کوردی",
        "movie_category" to "پۆلینی فیلم",
        "movie_release_year" to "ساڵی بەرهەمهێنان",
        "movie_duration" to "ماوەی فیلم (بە خولەک)",
        "movie_video_url" to "لینکی ڤیدیۆ یان پەخش",
        "movie_poster_select" to "وێنەی پۆستەری فیلم",
        "movie_synopsis_ku" to "کورتەی چیرۆک بە کوردی",
        "movie_synopsis_en" to "کورتەی چیرۆک بە ئینگلیزی",
        "save_movie" to "فیلمەکە تۆمار بکە و بڵاوی بکەوە",
        "movie_added_success" to "فیلم بە سەرکەوتوویی زیادکرا! ئێستا هەمووان دەتوانن سەیری بکەن.",
        "fill_required_fields" to "تکایە ناوی فیلم و بەستەری ڤیدیۆ پڕ بکەرەوە",
        "watchlist_empty" to "هیچ فیلمێک لە لیستەکەتدا نییە",
        "watchlist_empty_desc" to "لە کاتی سەیرکردنی فیلمەکان کلیک لەسەر + بکە بۆ خستنە ناو لیست",
        "video_player_quality" to "کوالیتی",
        "video_player_audio" to "دەنگی کوردی/ئۆریجیناڵ",
        "video_player_subtitles" to "ژێرنووس",
        "speed" to "خێرایی",
        "resume" to "دەستپێکردنەوە",
        "settings_language" to "زمانی ئەپڵیکەیشن",
        "settings_stream_quality" to "کوالیتی بنەڕەتی",
        "settings_auto_play" to "لێدانی خۆکار",
        "settings_stats" to "ئامارەکان",
        "total_movies" to "کۆی گشتی فیلمەکان",
        "user_movies" to "فیلمە زیادکراوەکانی تۆ",
        "all_categories" to "هەموو",
        "genre_action" to "ئەکشن",
        "genre_kurdish" to "سینەمای کوردی",
        "genre_drama" to "دراما",
        "genre_animation" to "ئەنیمەیشن",
        "genre_scifi" to "زانستی خەیاڵی",
        "genre_comedy" to "کۆمیدی",
        "genre_documentary" to "بەڵگەنامەیی",
        "select_preset_poster" to "یان یەکێک لەم پۆستەرانە هەڵبژێرە:",
        "pick_image_gallery" to "هەڵبژاردنی پووستەر لە تەلەفۆن",
        "uploading_poster" to "بارکردنی وێنە بۆ Firebase Storage...",
        "upload_success" to "وێنە بە سەرکەوتوویی ئەپلۆد کرا!",
        "custom_poster_selected" to "پووستەری تەلەفۆنەکەت",
        "poster_url_title" to "لینکی وێنەی پۆستەر (Poster Image URL)",
        "poster_url_hint" to "https://example.com/poster.jpg یان لینکی گووگڵ",
        "poster_url_desc" to "لینکی وێنەی پۆستەر لە گووگڵ یان هەر ماڵپەڕێک لێرە دابنێ تا ڕاستەوخۆ دەربکەوێت.",
        "live_preview_title" to "پێشبینینی ڕاستەوخۆی وێنەی پۆستەر (Live Preview)"
    )

    private val englishStrings = mapOf(
        "app_title" to "M1955 Cinema",
        "tagline" to "Kurdish & World Cinema Streaming Hub",
        "tab_home" to "Home",
        "tab_categories" to "Categories",
        "tab_add" to "Add Movie",
        "tab_watchlist" to "My List",
        "tab_settings" to "Settings",
        "search_hint" to "Search movies, actors, directors...",
        "featured" to "Featured Today",
        "trending" to "Trending Now",
        "kurdish_cinema" to "Kurdish Cinema 🌟",
        "M1955_cinema" to "M1955 Cinema 🌟",
        "continue_watching" to "Continue Watching",
        "top_rated" to "Top Rated Movies",
        "recently_added" to "Recently Added",
        "watch_now" to "Watch Now",
        "trailer" to "Trailer",
        "download" to "Download",
        "add_to_list" to "+ My List",
        "in_list" to "✓ In List",
        "share" to "Share",
        "synopsis" to "Synopsis",
        "cast_director" to "Cast & Crew",
        "director" to "Director",
        "cast" to "Cast",
        "languages" to "Languages & Subtitles",
        "quality" to "Quality",
        "reviews" to "User Reviews & Ratings",
        "add_review" to "Write a Review",
        "submit_review" to "Post Review",
        "your_rating" to "Your Rating",
        "your_name" to "Your Name",
        "your_comment" to "Share your thoughts about this movie...",
        "no_reviews" to "No reviews yet. Be the first to share your thoughts!",
        "add_movie_title" to "Add a New Movie",
        "add_movie_subtitle" to "Upload your movie link so everyone can stream and watch it",
        "movie_title_en" to "Movie Title (English)",
        "movie_title_ku" to "Movie Title (Kurdish)",
        "movie_category" to "Category / Genre",
        "movie_release_year" to "Release Year",
        "movie_duration" to "Duration (Minutes)",
        "movie_video_url" to "Video Stream / Trailer URL",
        "movie_poster_select" to "Movie Poster Selection",
        "movie_synopsis_ku" to "Synopsis in Kurdish",
        "movie_synopsis_en" to "Synopsis in English",
        "save_movie" to "Publish & Add Movie",
        "movie_added_success" to "Movie added successfully! Everyone can now stream and watch it.",
        "fill_required_fields" to "Please provide a movie title and video link",
        "watchlist_empty" to "Your watchlist is empty",
        "watchlist_empty_desc" to "Tap + on any movie to add it to your personal watchlist",
        "video_player_quality" to "Stream Quality",
        "video_player_audio" to "Audio Track",
        "video_player_subtitles" to "Subtitles",
        "speed" to "Speed",
        "resume" to "Resume Playback",
        "settings_language" to "App Language",
        "settings_stream_quality" to "Default Stream Quality",
        "settings_auto_play" to "Autoplay Next",
        "settings_stats" to "Cinema Statistics",
        "total_movies" to "Total Movies",
        "user_movies" to "Movies Added By You",
        "all_categories" to "All",
        "genre_action" to "Action",
        "genre_kurdish" to "Kurdish Cinema",
        "genre_drama" to "Drama",
        "genre_animation" to "Animation",
        "genre_scifi" to "Sci-Fi",
        "genre_comedy" to "Comedy",
        "genre_documentary" to "Documentary",
        "select_preset_poster" to "Or select a poster preset:",
        "pick_image_gallery" to "Choose Poster from Phone",
        "uploading_poster" to "Uploading Poster to Firebase Storage...",
        "upload_success" to "Poster uploaded successfully!",
        "custom_poster_selected" to "Custom Phone Poster",
        "poster_url_title" to "Movie Poster Image URL (from Google / Web)",
        "poster_url_hint" to "https://example.com/poster.jpg",
        "poster_url_desc" to "Paste any poster image link from Google Images or the web for instant live display.",
        "live_preview_title" to "Live Poster Preview"
    )
}
